export const PRICE_BY_USER_QTY = 25

export const SASS_SIGN_UP_MAIN_FEATURES = [
  'GESTÃO DE CONTATOS',
  'CONTROLE DE RELACIONAMENTO',
  'ACESSIBILIDADE MÓVEL',
  'CRIAÇÃO DE PROPOSTAS COMERCIAIS',
  'AUTOMAÇÕES DE MARKETING',
  'GESTÃO COMERCIAL',
  'ACOMPANHAMENTO DE RESULTADOS',
  'INTEGRAÇÕES DE MARKETING',
]
